import scss from './About.module.scss';
import { ReactComponent as IconCross } from '../../icons/cross.svg';
import image from '../../images/about/about-mobile.webp';
import AboutBanner from 'components/about-banner/AboutBanner';

const About = () => {
  return (
    <section>
      <div className={scss.container}>
        <h2 className={scss.title}>
          a Story that started <br /> with
          <span className={scss.titleSpan}>
            {' '}
            one <br />
            simple
            <br className={scss.breakMobile} /> ape
          </span>
        </h2>
        <p className={scss.description1}>
          WHO GOT
          <br className={scss.breakMobile} /> FED UP WITH BORING
          <br /> AND HYPOCRITIC
          <br className={scss.breakMobile} /> COMMONPLACE
          <br className={scss.breakTablet} /> THIS IS {''}
          <br className={scss.breakMobile} />
          HOW THE IDEA OF
          <br /> ESCAPING AND DYNAMIC <br />
          JOURNEY ON THE <br className={scss.breakTablet} /> YACHT
        </p>

        <div className={scss.descriptionWrapper}>
          <IconCross className={scss.iconCross} aria-label="icon cross" />
          <p className={scss.description2}>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </p>
        </div>

        <div className={scss.imageWrapper}>
          <img src={image} alt="monkey" className={scss.image} />
        </div>
      </div>

      <AboutBanner />
    </section>
  );
};

export default About;
